"""add the founders insight card table

Revision ID: 643ed82b1407
Revises: 0ca6335e5b80
Create Date: 2026-07-27 22:29:34.818084

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '643ed82b1407'
down_revision: Union[str, Sequence[str], None] = '0ca6335e5b80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('founder_insight_cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('highlight_stat', sa.String(length=50), nullable=True),
    sa.Column('insight_text', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('accent_color', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_founder_insight_cards_id'), 'founder_insight_cards', ['id'], unique=False)
    op.drop_index(op.f('idx_alerts_created_at'), table_name='alerts')
    op.drop_index(op.f('idx_alerts_is_active'), table_name='alerts')
    op.drop_index(op.f('idx_ba_created_at'), table_name='business_analyses')
    op.drop_index(op.f('idx_ba_user_id'), table_name='business_analyses')
    op.drop_index(op.f('idx_channel_members_channel'), table_name='channel_members')
    op.drop_index(op.f('idx_channel_members_user'), table_name='channel_members')
    op.drop_index(op.f('idx_cm_channel_id'), table_name='channel_members')
    op.drop_index(op.f('idx_cm_user_id'), table_name='channel_members')
    op.drop_index(op.f('idx_cs_user_id'), table_name='commission_summaries')
    op.drop_index(op.f('idx_com_created_at'), table_name='commissions')
    op.drop_index(op.f('idx_com_referred_id'), table_name='commissions')
    op.drop_index(op.f('idx_com_status'), table_name='commissions')
    op.drop_index(op.f('idx_com_sub_id'), table_name='commissions')
    op.drop_index(op.f('idx_com_user_id'), table_name='commissions')
    op.drop_index(op.f('idx_community_activities_user'), table_name='community_activities')
    op.drop_index(op.f('idx_cd_channel_id'), table_name='community_discussions')
    op.drop_index(op.f('idx_cd_user_id'), table_name='community_discussions')
    op.drop_index(op.f('idx_discussions_channel'), table_name='community_discussions')
    op.drop_index(op.f('idx_discussions_user'), table_name='community_discussions')
    op.drop_index(op.f('idx_conv_is_read'), table_name='conversations')
    op.drop_index(op.f('idx_conv_review_id'), table_name='conversations')
    op.drop_index(op.f('idx_dl_user_id'), table_name='discussion_likes')
    op.drop_index(op.f('idx_dr_discussion_id'), table_name='discussion_replies')
    op.drop_index(op.f('idx_insights_created_at'), table_name='insights')
    op.drop_index(op.f('idx_insights_is_active'), table_name='insights')
    op.drop_index(op.f('idx_mp_status'), table_name='marketplace_purchases')
    op.drop_index(op.f('idx_mp_tool_id'), table_name='marketplace_purchases')
    op.drop_index(op.f('idx_mp_user_id'), table_name='marketplace_purchases')
    op.drop_index(op.f('idx_pa_user_id'), table_name='payout_accounts')
    op.create_unique_constraint(None, 'payout_accounts', ['user_id'])
    op.drop_index(op.f('idx_payout_status'), table_name='payouts')
    op.drop_index(op.f('idx_payout_user_id'), table_name='payouts')
    op.drop_index(op.f('idx_ref_referred_id'), table_name='referrals')
    op.drop_index(op.f('idx_ref_referrer_id'), table_name='referrals')
    op.drop_index(op.f('idx_reviews_user_id'), table_name='reviews')
    op.drop_column('reviews', 'is_attended')
    op.drop_index(op.f('idx_saved_items_user'), table_name='saved_items')
    op.drop_index(op.f('idx_si_composite'), table_name='saved_items')
    op.drop_index(op.f('idx_si_user_id'), table_name='saved_items')
    op.drop_index(op.f('idx_sub_created_at'), table_name='subscriptions')
    op.drop_index(op.f('idx_sub_status'), table_name='subscriptions')
    op.drop_index(op.f('idx_sub_user_id'), table_name='subscriptions')
    op.drop_index(op.f('idx_ua_alert_id'), table_name='user_alerts')
    op.drop_index(op.f('idx_ua_composite'), table_name='user_alerts')
    op.drop_index(op.f('idx_ua_user_id'), table_name='user_alerts')
    op.drop_index(op.f('idx_ui_insight_id'), table_name='user_insights')
    op.drop_index(op.f('idx_ui_user_id'), table_name='user_insights')
    op.drop_index(op.f('idx_um_user_id'), table_name='user_missions')
    op.drop_index(op.f('idx_un_created_at'), table_name='user_notifications')
    op.drop_index(op.f('idx_un_user_id'), table_name='user_notifications')
    op.drop_index(op.f('idx_user_notifications_user_unread'), table_name='user_notifications')
    op.drop_index(op.f('idx_upa_alert_id'), table_name='user_pinned_alerts')
    op.drop_index(op.f('idx_upa_composite'), table_name='user_pinned_alerts')
    op.drop_index(op.f('idx_upa_user_id'), table_name='user_pinned_alerts')
    op.drop_index(op.f('idx_upi_user_id'), table_name='user_pinned_insights')
    op.drop_index(op.f('idx_users_created_at'), table_name='users')
    op.drop_index(op.f('idx_users_is_active'), table_name='users')
    op.drop_index(op.f('idx_users_sub_status'), table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_users_sub_status'), 'users', ['subscription_status'], unique=False)
    op.create_index(op.f('idx_users_is_active'), 'users', ['is_active'], unique=False)
    op.create_index(op.f('idx_users_created_at'), 'users', [sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('idx_upi_user_id'), 'user_pinned_insights', ['user_id'], unique=False)
    op.create_index(op.f('idx_upa_user_id'), 'user_pinned_alerts', ['user_id'], unique=False)
    op.create_index(op.f('idx_upa_composite'), 'user_pinned_alerts', ['user_id', 'alert_id'], unique=False)
    op.create_index(op.f('idx_upa_alert_id'), 'user_pinned_alerts', ['alert_id'], unique=False)
    op.create_index(op.f('idx_user_notifications_user_unread'), 'user_notifications', ['user_id', 'is_read'], unique=False)
    op.create_index(op.f('idx_un_user_id'), 'user_notifications', ['user_id'], unique=False)
    op.create_index(op.f('idx_un_created_at'), 'user_notifications', [sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('idx_um_user_id'), 'user_missions', ['user_id'], unique=False)
    op.create_index(op.f('idx_ui_user_id'), 'user_insights', ['user_id'], unique=False)
    op.create_index(op.f('idx_ui_insight_id'), 'user_insights', ['insight_id'], unique=False)
    op.create_index(op.f('idx_ua_user_id'), 'user_alerts', ['user_id'], unique=False)
    op.create_index(op.f('idx_ua_composite'), 'user_alerts', ['user_id', 'alert_id'], unique=False)
    op.create_index(op.f('idx_ua_alert_id'), 'user_alerts', ['alert_id'], unique=False)
    op.create_index(op.f('idx_sub_user_id'), 'subscriptions', ['user_id'], unique=False)
    op.create_index(op.f('idx_sub_status'), 'subscriptions', ['subscription_status'], unique=False)
    op.create_index(op.f('idx_sub_created_at'), 'subscriptions', [sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('idx_si_user_id'), 'saved_items', ['user_id'], unique=False)
    op.create_index(op.f('idx_si_composite'), 'saved_items', ['user_id', 'item_type'], unique=False)
    op.create_index(op.f('idx_saved_items_user'), 'saved_items', ['user_id'], unique=False)
    op.add_column('reviews', sa.Column('is_attended', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.create_index(op.f('idx_reviews_user_id'), 'reviews', ['user_id'], unique=False)
    op.create_index(op.f('idx_ref_referrer_id'), 'referrals', ['referrer_id'], unique=False)
    op.create_index(op.f('idx_ref_referred_id'), 'referrals', ['referred_user_id'], unique=False)
    op.create_index(op.f('idx_payout_user_id'), 'payouts', ['user_id'], unique=False)
    op.create_index(op.f('idx_payout_status'), 'payouts', ['status'], unique=False)
    op.drop_constraint(None, 'payout_accounts', type_='unique')
    op.create_index(op.f('idx_pa_user_id'), 'payout_accounts', ['user_id'], unique=False)
    op.create_index(op.f('idx_mp_user_id'), 'marketplace_purchases', ['user_id'], unique=False)
    op.create_index(op.f('idx_mp_tool_id'), 'marketplace_purchases', ['tool_id'], unique=False)
    op.create_index(op.f('idx_mp_status'), 'marketplace_purchases', ['status'], unique=False)
    op.create_index(op.f('idx_insights_is_active'), 'insights', ['is_active'], unique=False)
    op.create_index(op.f('idx_insights_created_at'), 'insights', [sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('idx_dr_discussion_id'), 'discussion_replies', ['discussion_id'], unique=False)
    op.create_index(op.f('idx_dl_user_id'), 'discussion_likes', ['user_id'], unique=False)
    op.create_index(op.f('idx_conv_review_id'), 'conversations', ['review_id'], unique=False)
    op.create_index(op.f('idx_conv_is_read'), 'conversations', ['is_read'], unique=False)
    op.create_index(op.f('idx_discussions_user'), 'community_discussions', ['user_id'], unique=False)
    op.create_index(op.f('idx_discussions_channel'), 'community_discussions', ['channel_id'], unique=False)
    op.create_index(op.f('idx_cd_user_id'), 'community_discussions', ['user_id'], unique=False)
    op.create_index(op.f('idx_cd_channel_id'), 'community_discussions', ['channel_id'], unique=False)
    op.create_index(op.f('idx_community_activities_user'), 'community_activities', ['user_id'], unique=False)
    op.create_index(op.f('idx_com_user_id'), 'commissions', ['user_id'], unique=False)
    op.create_index(op.f('idx_com_sub_id'), 'commissions', ['subscription_id'], unique=False)
    op.create_index(op.f('idx_com_status'), 'commissions', ['status'], unique=False)
    op.create_index(op.f('idx_com_referred_id'), 'commissions', ['referred_user_id'], unique=False)
    op.create_index(op.f('idx_com_created_at'), 'commissions', [sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('idx_cs_user_id'), 'commission_summaries', ['user_id'], unique=False)
    op.create_index(op.f('idx_cm_user_id'), 'channel_members', ['user_id'], unique=False)
    op.create_index(op.f('idx_cm_channel_id'), 'channel_members', ['channel_id'], unique=False)
    op.create_index(op.f('idx_channel_members_user'), 'channel_members', ['user_id'], unique=False)
    op.create_index(op.f('idx_channel_members_channel'), 'channel_members', ['channel_id'], unique=False)
    op.create_index(op.f('idx_ba_user_id'), 'business_analyses', ['user_id'], unique=False)
    op.create_index(op.f('idx_ba_created_at'), 'business_analyses', [sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('idx_alerts_is_active'), 'alerts', ['is_active'], unique=False)
    op.create_index(op.f('idx_alerts_created_at'), 'alerts', [sa.literal_column('created_at DESC')], unique=False)
    op.drop_index(op.f('ix_founder_insight_cards_id'), table_name='founder_insight_cards')
    op.drop_table('founder_insight_cards')
    # ### end Alembic commands ###